import path from 'node:path';
import type {
  NormalizedApiKitConfig,
  NormalizedHookCallDefinition,
  NormalizedResourceDefinition,
} from '../compiler/models';
import type { ResourceEndpointName } from '../definition/types';
import { resolveDbProviderToken } from '../compiler/resource-source';
import { buildControllerImportConfig, type ControllerImportConfig } from './template-imports';

type SerializableResourceTemplateModel = Omit<NormalizedResourceDefinition, 'original'> & {
  original: {
    route?: {
      tag?: string;
    };
    query?: {
      baseQueryName?: string;
    };
  };
};

export type ResourceTemplateContext = {
  generatedHeader: string;
  resourceDir: string;
  dtoDir: string;
  targets: {
    createDto: string;
    updateDto: string;
    findQueryDto: string;
    idParamsDto: string;
    responseDto: string;
    metadata: string;
    service: string;
    query: string;
    controller: string;
    module: string;
    index: string;
  };
  resource: SerializableResourceTemplateModel;
  guards: {
    names: string[];
    importPath: string | null;
  };
  controller: ControllerImportConfig;
  hooks?: Record<ResourceEndpointName, {
    before: Array<{
      constName: string;
      resolveExpression: string;
      description?: string;
    }>;
    after: Array<{
      constName: string;
      resolveExpression: string;
      description?: string;
    }>;
  }>;
  imports: {
    tableImportPath: string;
    tableImportKind: 'default' | 'named' | 'namespace';
    tableImportName: string;
    tableImportSourceName: string;
    tableAccessExpression: string;
    tableQueryName: string;
    dbSchemaImportPath?: string;
    dbSchemaImportKind?: 'default' | 'named' | 'namespace';
    dbSchemaImportName?: string;
    dbSchemaImportSourceName?: string;
    dbSchemaAccessExpression?: string;
    dbProviderToken: string;
    commonTypesImportPath: string;
    commonQueryImportPath: string;
    commonHooksImportPath: string;
    commonValidationImportPath: string;
    validationImportPath?: string;
    validationImportKind?: 'default' | 'named' | 'namespace';
    validationImportName?: string;
    validationImportSourceName?: string;
    validationAccessExpression?: string;
    configHooksImportPath?: string;
    configHooksImportKind?: 'default' | 'named' | 'namespace';
    configHooksImportName?: string;
    configHooksImportSourceName?: string;
    configHooksAccessExpression?: string;
    resourceHooksImportPath?: string;
    resourceHooksImportKind?: 'default' | 'named' | 'namespace';
    resourceHooksImportName?: string;
    resourceHooksImportSourceName?: string;
    resourceHooksAccessExpression?: string;
  };
};

export type RootTemplateContext = {
  generatedHeader: string;
  outputPath: string;
  rootModuleClassName: string;
  rootModuleFileName: string;
  dbProviderToken: string;
  dbSchemaImportPath?: string;
  dbSchemaImportKind?: 'default' | 'named' | 'namespace';
  dbSchemaImportName?: string;
  dbSchemaImportSourceName?: string;
  dbSchemaAccessExpression?: string;
  validation?: {
    engineName: 'zod' | 'custom';
    engineImportPath?: string;
    engineImportKind?: 'default' | 'named' | 'namespace';
    engineImportName?: string;
    engineImportSourceName?: string;
    engineAccessExpression?: string;
  };
  targets: {
    rootModule: string;
    index: string;
    commonDb: string;
    commonTypes: string;
    commonQuery: string;
    commonHooks: string;
    commonValidation: string;
    commonIndex: string;
  };
  resources: Array<{
    pluralName: string;
    moduleClassName: string;
  }>;
};

const GENERATED_HEADER = '// AUTO-GENERATED BY nest-drizzle-api-kit. DO NOT EDIT.';

function inferGuardImportPath(resource: NormalizedResourceDefinition): string | null {
  const candidate = resource.original.route?.tag;
  return candidate && candidate.startsWith('.') ? candidate : null;
}

function uniquifyHookCallNames(
  entries: Array<{ suggestedName: string }>,
): string[] {
  const counts = new Map<string, number>();

  return entries.map(({ suggestedName }) => {
    const nextCount = (counts.get(suggestedName) ?? 0) + 1;
    counts.set(suggestedName, nextCount);
    return nextCount === 1 ? suggestedName : `${suggestedName}${nextCount}`;
  });
}

function buildHookCalls(
  entries: Array<NormalizedHookCallDefinition & { rootAccessExpression: string }>,
): Array<{
  constName: string;
  resolveExpression: string;
  description?: string;
}> {
  const names = uniquifyHookCallNames(entries);

  return entries.map((entry, index) => ({
    constName: names[index]!,
    resolveExpression: `${entry.rootAccessExpression}${entry.accessor}`,
    ...(entry.description ? { description: entry.description } : {}),
  }));
}

export function buildResourceTemplateContext(
  config: NormalizedApiKitConfig,
  resource: NormalizedResourceDefinition,
): ResourceTemplateContext {
  const outputPath = config.outputPath;
  const resourceDir = path.join(outputPath, resource.pluralName);
  const dtoDir = path.join(resourceDir, 'dto');
  const servicePath = path.join(resourceDir, resource.fileNames.service);
  const guardNames = Array.from(
    new Set((resource.guards.resource ?? []).map((guard) => guard.name).filter(Boolean)),
  ).sort();
  const dbProviderToken = resolveDbProviderToken(config);
  const controller = buildControllerImportConfig(resource);
  const configHooksImportAlias = '__apiKitConfigHooksSource';
  const resourceHooksImportAlias = '__apiKitResourceHooksSource';
  const configHooksAccessExpression = config.hooks
    ? rewriteRootIdentifier(config.hooks.source.accessExpression, config.hooks.source.importName, configHooksImportAlias)
    : undefined;
  const resourceHooksAccessExpression = resource.hooks
    ? rewriteRootIdentifier(resource.hooks.source.accessExpression, resource.hooks.source.importName, resourceHooksImportAlias)
    : undefined;
  const serializableResource: SerializableResourceTemplateModel = {
    ...resource,
    original: {
      ...(resource.original.route?.tag ? { route: { tag: resource.original.route.tag } } : {}),
      ...(resource.original.query?.baseQuery
        ? { query: { baseQueryName: resource.original.query.baseQuery.name } }
        : {}),
    },
  };
  const hooks = Object.fromEntries(
    (['find', 'findOne', 'create', 'update', 'delete'] as ResourceEndpointName[]).map((endpointName) => {
      const before = buildHookCalls([
        ...(config.hooks?.before.map((entry) => ({
          ...entry,
          rootAccessExpression: configHooksAccessExpression!,
        })) ?? []),
        ...(config.hooks?.endpoints[endpointName].before.map((entry) => ({
          ...entry,
          rootAccessExpression: configHooksAccessExpression!,
        })) ?? []),
        ...(resource.hooks?.before.map((entry) => ({
          ...entry,
          rootAccessExpression: resourceHooksAccessExpression!,
        })) ?? []),
        ...(resource.hooks?.endpoints[endpointName].before.map((entry) => ({
          ...entry,
          rootAccessExpression: resourceHooksAccessExpression!,
        })) ?? []),
      ]);
      const after = buildHookCalls([
        ...(resource.hooks?.endpoints[endpointName].after.map((entry) => ({
          ...entry,
          rootAccessExpression: resourceHooksAccessExpression!,
        })) ?? []),
        ...(resource.hooks?.after.map((entry) => ({
          ...entry,
          rootAccessExpression: resourceHooksAccessExpression!,
        })) ?? []),
        ...(config.hooks?.endpoints[endpointName].after.map((entry) => ({
          ...entry,
          rootAccessExpression: configHooksAccessExpression!,
        })) ?? []),
        ...(config.hooks?.after.map((entry) => ({
          ...entry,
          rootAccessExpression: configHooksAccessExpression!,
        })) ?? []),
      ]);

      return [endpointName, { before, after }];
    }),
  ) as ResourceTemplateContext['hooks'];

  return {
    generatedHeader: GENERATED_HEADER,
    resourceDir,
    dtoDir,
    targets: {
      createDto: path.join(dtoDir, resource.fileNames.createDto),
      updateDto: path.join(dtoDir, resource.fileNames.updateDto),
      findQueryDto: path.join(dtoDir, resource.fileNames.findQueryDto),
      idParamsDto: path.join(dtoDir, resource.fileNames.idParamsDto),
      responseDto: path.join(dtoDir, resource.fileNames.responseDto),
      metadata: path.join(resourceDir, resource.fileNames.metadata),
      service: path.join(resourceDir, resource.fileNames.service),
      query: path.join(resourceDir, resource.fileNames.query),
      controller: path.join(resourceDir, resource.fileNames.controller),
      module: path.join(resourceDir, resource.fileNames.module),
      index: path.join(resourceDir, 'index.ts'),
    },
    resource: serializableResource,
    guards: {
      names: guardNames,
      importPath: inferGuardImportPath(resource),
    },
    controller,
    ...(hooks ? { hooks } : {}),
    imports: {
      tableImportPath: toModuleImport(servicePath, path.resolve(path.dirname(resource.source.sourceFile), resource.source.tableImportSourceFile)),
      tableImportKind: resource.source.tableImportKind,
      tableImportName: resource.source.tableImportName,
      tableImportSourceName: resource.source.tableImportSourceName,
      tableAccessExpression: resource.source.tableAccessExpression,
      tableQueryName: resource.source.tableQueryName,
      ...(config.dbSchemaSource
        ? {
            dbSchemaImportPath: toModuleImport(path.join(outputPath, 'common', 'db.ts'), config.dbSchemaSource.sourceFile),
            dbSchemaImportKind: config.dbSchemaSource.importKind,
            dbSchemaImportName: config.dbSchemaSource.importName,
            dbSchemaImportSourceName: config.dbSchemaSource.importSourceName,
            dbSchemaAccessExpression: config.dbSchemaSource.accessExpression,
          }
        : {}),
      dbProviderToken,
      commonTypesImportPath: toModuleImport(servicePath, path.join(outputPath, 'common', 'types.ts')),
      commonQueryImportPath: toModuleImport(servicePath, path.join(outputPath, 'common', 'query.ts')),
      commonHooksImportPath: toModuleImport(servicePath, path.join(outputPath, 'common', 'hooks.ts')),
      commonValidationImportPath: toModuleImport(servicePath, path.join(outputPath, 'common', 'validation.ts')),
      ...(resource.validation
        ? {
            validationImportPath: toModuleImport(
              servicePath,
              resource.validation.schemaSource.sourceFile,
            ),
            validationImportKind: resource.validation.schemaSource.importKind,
            validationImportName: resource.validation.schemaSource.importName,
            validationImportSourceName: resource.validation.schemaSource.importSourceName,
            validationAccessExpression: resource.validation.schemaSource.accessExpression,
          }
        : {}),
      ...(config.hooks
        ? {
            configHooksImportPath: toModuleImport(servicePath, config.hooks.source.sourceFile),
            configHooksImportKind: config.hooks.source.importKind,
            configHooksImportName: configHooksImportAlias,
            configHooksImportSourceName: config.hooks.source.importSourceName,
            configHooksAccessExpression: configHooksAccessExpression!,
          }
        : {}),
      ...(resource.hooks
        ? {
            resourceHooksImportPath: toModuleImport(servicePath, resource.hooks.source.sourceFile),
            resourceHooksImportKind: resource.hooks.source.importKind,
            resourceHooksImportName: resourceHooksImportAlias,
            resourceHooksImportSourceName: resource.hooks.source.importSourceName,
            resourceHooksAccessExpression: resourceHooksAccessExpression!,
          }
        : {}),
    },
  };
}

function toModuleImport(fromFile: string, toFile: string): string {
  const relativePath = path
    .relative(path.dirname(fromFile), toFile)
    .replace(/\\/g, '/')
    .replace(/\.(ts|tsx|js|jsx|mjs|cjs)$/i, '');
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
}

function rewriteRootIdentifier(expression: string, from: string, to: string): string {
  return expression.replace(new RegExp(`^${from}(?=\\.|$)`), to);
}

export function buildRootTemplateContext(config: NormalizedApiKitConfig): RootTemplateContext {
  const commonTypesPath = path.join(config.outputPath, 'common', 'types.ts');
  const commonDbPath = path.join(config.outputPath, 'common', 'db.ts');
  const schemaImportAlias = '__apiKitSchemaSource';

  return {
    generatedHeader: GENERATED_HEADER,
    outputPath: config.outputPath,
    rootModuleClassName: config.rootModuleClassName,
    rootModuleFileName: config.rootModuleFileName,
    dbProviderToken: resolveDbProviderToken(config),
    ...(config.dbSchemaSource
      ? {
          dbSchemaImportPath: toModuleImport(commonDbPath, config.dbSchemaSource.sourceFile),
          dbSchemaImportKind: config.dbSchemaSource.importKind,
          dbSchemaImportName: schemaImportAlias,
          dbSchemaImportSourceName: config.dbSchemaSource.importSourceName,
          dbSchemaAccessExpression: rewriteRootIdentifier(
            config.dbSchemaSource.accessExpression,
            config.dbSchemaSource.importName,
            schemaImportAlias,
          ),
        }
      : {}),
    ...(config.validation
      ? {
          validation: config.validation.engineSource
            ? {
                engineName: 'custom' as const,
                engineImportPath: toModuleImport(commonDbPath, config.validation.engineSource.sourceFile),
                engineImportKind: config.validation.engineSource.importKind,
                engineImportName: config.validation.engineSource.importName,
                engineImportSourceName: config.validation.engineSource.importSourceName,
                engineAccessExpression: rewriteRootIdentifier(
                  config.validation.engineSource.accessExpression,
                  config.validation.engineSource.importName,
                  config.validation.engineSource.importName,
                ),
              }
            : {
                engineName: 'zod' as const,
              },
        }
      : {}),
    targets: {
      rootModule: path.join(config.outputPath, config.rootModuleFileName),
      index: path.join(config.outputPath, 'index.ts'),
      commonDb: commonDbPath,
      commonTypes: commonTypesPath,
      commonQuery: path.join(config.outputPath, 'common', 'query.ts'),
      commonHooks: path.join(config.outputPath, 'common', 'hooks.ts'),
      commonValidation: path.join(config.outputPath, 'common', 'validation.ts'),
      commonIndex: path.join(config.outputPath, 'common', 'index.ts'),
    },
    resources: config.resources.map((resource) => ({
      pluralName: resource.pluralName,
      moduleClassName: resource.classNames.module,
    })),
  };
}
