import path from 'node:path';
import type { NormalizedApiKitConfig, NormalizedResourceDefinition } from '../compiler/models';
import { resolveDbProviderToken } from '../compiler/resource-source';
import { buildControllerImportConfig, type ControllerImportConfig } from './template-imports';

type SerializableResourceTemplateModel = Omit<NormalizedResourceDefinition, 'original'> & {
  original: {
    route?: {
      tag?: string;
    };
    query?: {
      baseQueryName?: string;
    };
  };
};

export type ResourceTemplateContext = {
  generatedHeader: string;
  resourceDir: string;
  dtoDir: string;
  targets: {
    createDto: string;
    updateDto: string;
    findQueryDto: string;
    idParamsDto: string;
    responseDto: string;
    metadata: string;
    service: string;
    query: string;
    controller: string;
    module: string;
    index: string;
  };
  resource: SerializableResourceTemplateModel;
  guards: {
    names: string[];
    importPath: string | null;
  };
  controller: ControllerImportConfig;
  imports: {
    tableImportPath: string;
    tableImportKind: 'default' | 'named' | 'namespace';
    tableImportName: string;
    tableImportSourceName: string;
    tableAccessExpression: string;
    tableQueryName: string;
    dbSchemaImportPath?: string;
    dbSchemaImportKind?: 'default' | 'named' | 'namespace';
    dbSchemaImportName?: string;
    dbSchemaImportSourceName?: string;
    dbSchemaAccessExpression?: string;
    dbProviderToken: string;
    commonTypesImportPath: string;
    commonQueryImportPath: string;
  };
};

export type RootTemplateContext = {
  generatedHeader: string;
  outputPath: string;
  rootModuleClassName: string;
  rootModuleFileName: string;
  dbProviderToken: string;
  dbSchemaImportPath?: string;
  dbSchemaImportKind?: 'default' | 'named' | 'namespace';
  dbSchemaImportName?: string;
  dbSchemaImportSourceName?: string;
  dbSchemaAccessExpression?: string;
  targets: {
    rootModule: string;
    index: string;
    commonDb: string;
    commonTypes: string;
    commonQuery: string;
    commonIndex: string;
  };
  resources: Array<{
    pluralName: string;
    moduleClassName: string;
  }>;
};

const GENERATED_HEADER = '// AUTO-GENERATED BY nest-drizzle-api-kit. DO NOT EDIT.';

function inferGuardImportPath(resource: NormalizedResourceDefinition): string | null {
  const candidate = resource.original.route?.tag;
  return candidate && candidate.startsWith('.') ? candidate : null;
}

export function buildResourceTemplateContext(
  config: NormalizedApiKitConfig,
  resource: NormalizedResourceDefinition,
): ResourceTemplateContext {
  const outputPath = config.outputPath;
  const resourceDir = path.join(outputPath, resource.pluralName);
  const dtoDir = path.join(resourceDir, 'dto');
  const servicePath = path.join(resourceDir, resource.fileNames.service);
  const guardNames = Array.from(
    new Set((resource.guards.resource ?? []).map((guard) => guard.name).filter(Boolean)),
  ).sort();
  const dbProviderToken = resolveDbProviderToken(config);
  const controller = buildControllerImportConfig(resource);
  const serializableResource: SerializableResourceTemplateModel = {
    ...resource,
    original: {
      ...(resource.original.route?.tag ? { route: { tag: resource.original.route.tag } } : {}),
      ...(resource.original.query?.baseQuery
        ? { query: { baseQueryName: resource.original.query.baseQuery.name } }
        : {}),
    },
  };

  return {
    generatedHeader: GENERATED_HEADER,
    resourceDir,
    dtoDir,
    targets: {
      createDto: path.join(dtoDir, resource.fileNames.createDto),
      updateDto: path.join(dtoDir, resource.fileNames.updateDto),
      findQueryDto: path.join(dtoDir, resource.fileNames.findQueryDto),
      idParamsDto: path.join(dtoDir, resource.fileNames.idParamsDto),
      responseDto: path.join(dtoDir, resource.fileNames.responseDto),
      metadata: path.join(resourceDir, resource.fileNames.metadata),
      service: path.join(resourceDir, resource.fileNames.service),
      query: path.join(resourceDir, resource.fileNames.query),
      controller: path.join(resourceDir, resource.fileNames.controller),
      module: path.join(resourceDir, resource.fileNames.module),
      index: path.join(resourceDir, 'index.ts'),
    },
    resource: serializableResource,
    guards: {
      names: guardNames,
      importPath: inferGuardImportPath(resource),
    },
    controller,
    imports: {
      tableImportPath: toModuleImport(servicePath, path.resolve(path.dirname(resource.source.sourceFile), resource.source.tableImportSourceFile)),
      tableImportKind: resource.source.tableImportKind,
      tableImportName: resource.source.tableImportName,
      tableImportSourceName: resource.source.tableImportSourceName,
      tableAccessExpression: resource.source.tableAccessExpression,
      tableQueryName: resource.source.tableQueryName,
      ...(config.dbSchemaSource
        ? {
            dbSchemaImportPath: toModuleImport(path.join(outputPath, 'common', 'db.ts'), config.dbSchemaSource.sourceFile),
            dbSchemaImportKind: config.dbSchemaSource.importKind,
            dbSchemaImportName: config.dbSchemaSource.importName,
            dbSchemaImportSourceName: config.dbSchemaSource.importSourceName,
            dbSchemaAccessExpression: config.dbSchemaSource.accessExpression,
          }
        : {}),
      dbProviderToken,
      commonTypesImportPath: toModuleImport(servicePath, path.join(outputPath, 'common', 'types.ts')),
      commonQueryImportPath: toModuleImport(servicePath, path.join(outputPath, 'common', 'query.ts')),
    },
  };
}

function toModuleImport(fromFile: string, toFile: string): string {
  const relativePath = path
    .relative(path.dirname(fromFile), toFile)
    .replace(/\\/g, '/')
    .replace(/\.(ts|tsx|js|jsx|mjs|cjs)$/i, '');
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
}

function rewriteRootIdentifier(expression: string, from: string, to: string): string {
  return expression.replace(new RegExp(`^${from}(?=\\.|$)`), to);
}

export function buildRootTemplateContext(config: NormalizedApiKitConfig): RootTemplateContext {
  const commonTypesPath = path.join(config.outputPath, 'common', 'types.ts');
  const commonDbPath = path.join(config.outputPath, 'common', 'db.ts');
  const schemaImportAlias = '__apiKitSchemaSource';

  return {
    generatedHeader: GENERATED_HEADER,
    outputPath: config.outputPath,
    rootModuleClassName: config.rootModuleClassName,
    rootModuleFileName: config.rootModuleFileName,
    dbProviderToken: resolveDbProviderToken(config),
    ...(config.dbSchemaSource
      ? {
          dbSchemaImportPath: toModuleImport(commonDbPath, config.dbSchemaSource.sourceFile),
          dbSchemaImportKind: config.dbSchemaSource.importKind,
          dbSchemaImportName: schemaImportAlias,
          dbSchemaImportSourceName: config.dbSchemaSource.importSourceName,
          dbSchemaAccessExpression: rewriteRootIdentifier(
            config.dbSchemaSource.accessExpression,
            config.dbSchemaSource.importName,
            schemaImportAlias,
          ),
        }
      : {}),
    targets: {
      rootModule: path.join(config.outputPath, config.rootModuleFileName),
      index: path.join(config.outputPath, 'index.ts'),
      commonDb: commonDbPath,
      commonTypes: commonTypesPath,
      commonQuery: path.join(config.outputPath, 'common', 'query.ts'),
      commonIndex: path.join(config.outputPath, 'common', 'index.ts'),
    },
    resources: config.resources.map((resource) => ({
      pluralName: resource.pluralName,
      moduleClassName: resource.classNames.module,
    })),
  };
}
