import fs from 'node:fs';
import path from 'node:path';
import type {
  ImportedValueSource,
  NormalizedApiKitConfig,
  NormalizedDtoDefinition,
  NormalizedGeneratedDtoDefinition,
  NormalizedHookDefinition,
  NormalizedResourceDefinition,
  NormalizedResourceFunctionDefinition,
} from '../compiler/models';
import type { ResourceFunctionName } from '../definition/types';
import { resolveDbProviderToken } from '../compiler/resource-source';
import { kebabCase, pascalCase } from '../compiler/naming';

const ejs = require('ejs');

const GENERATED_HEADER = '// AUTO-GENERATED BY nest-drizzle-api-kit. DO NOT EDIT.';
const PARTIALS_DIR = path.resolve(__dirname, '..', '..', '_templates', '_partials', 'resource');
const functionNames: ResourceFunctionName[] = ['find', 'findOne', 'create', 'update', 'delete'];

type GeneratedDtoTemplateTargets = {
  findInputDto: string;
  createInputDto: string;
  updateInputDto: string;
  idParamsDto: string;
  findOutputDto: string;
  findOneOutputDto: string;
  createOutputDto: string;
  updateOutputDto: string;
};

type GeneratedDtoTemplateContext = {
  findInput?: NormalizedGeneratedDtoDefinition;
  createInput?: NormalizedGeneratedDtoDefinition;
  updateInput?: NormalizedGeneratedDtoDefinition;
  idParams?: Pick<NormalizedGeneratedDtoDefinition, 'mode' | 'kind' | 'className' | 'fileName'>;
  findOutput?: NormalizedGeneratedDtoDefinition;
  findOneOutput?: NormalizedGeneratedDtoDefinition;
  createOutput?: NormalizedGeneratedDtoDefinition;
  updateOutput?: NormalizedGeneratedDtoDefinition;
};

export type ResourceTemplateContext = {
  generatedHeader: string;
  resourceDir: string;
  dtoDir: string;
  targets: GeneratedDtoTemplateTargets & {
    metadata: string;
    service: string;
    query: string;
    controller: string;
    module: string;
    index: string;
  };
  resource: Omit<NormalizedResourceDefinition, 'original'>;
  dto: GeneratedDtoTemplateContext;
  controller: {
    importsBlock: string;
    apiTagsDecorator: string | null;
    guardDecorator: string | null;
    bigIntParserMethod: string | null;
    methods: string;
  };
  service: {
    importsBlock: string;
    dbType: string;
    findMethod: string;
    findOneMethod: string;
    createMethod: string;
    updateMethod: string;
    deleteMethod: string;
  };
  query: {
    enabled: boolean;
    importsBlock: string;
    drizzleImports: string;
    dbType: string;
    findManyMethod: string;
    findOneMethod: string;
    resolveConditionMethod: string;
    resolveOrderByMethod: string | null;
  };
  indexExports: string[];
};

export type RootTemplateContext = {
  generatedHeader: string;
  outputPath: string;
  rootModuleClassName: string;
  rootModuleFileName: string;
  dbProviderToken: string;
  dbSchemaImportPath?: string;
  dbSchemaImportKind?: 'default' | 'named' | 'namespace';
  dbSchemaImportName?: string;
  dbSchemaImportSourceName?: string;
  dbSchemaAccessExpression?: string;
  validation?: {
    engineImportPath?: string;
    engineImportKind?: 'default' | 'named' | 'namespace';
    engineImportName?: string;
    engineImportSourceName?: string;
    engineAccessExpression?: string;
  };
  targets: {
    rootModule: string;
    index: string;
    commonDb: string;
    commonTypes: string;
    commonQuery: string;
    commonValidation: string;
    commonIndex: string;
  };
  resources: Array<{
    pluralName: string;
    moduleClassName: string;
  }>;
};

type ImportEntry = {
  key: string;
  importKind: 'default' | 'named' | 'namespace';
  importPath: string;
  importSourceName: string;
  localName: string;
};

type ControllerImportConfig = {
  commonImports: string[];
  usesBigIntIdParser: boolean;
  usesNumberIdPipe: boolean;
};

function renderPartialTemplate(templatePath: string, locals: Record<string, unknown>): string {
  const template = fs.readFileSync(path.join(PARTIALS_DIR, templatePath), 'utf8');
  return ejs.render(template, locals);
}

function joinBlocks(blocks: Array<string | null | undefined>, separator = '\n\n'): string {
  return blocks.filter((block): block is string => Boolean(block && block.trim().length > 0)).join(separator);
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function toModuleImport(fromFile: string, toFile: string): string {
  const relativePath = path
    .relative(path.dirname(fromFile), toFile)
    .replace(/\\/g, '/')
    .replace(/\.(ts|tsx|js|jsx|mjs|cjs)$/i, '');
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
}

function rewriteRootIdentifier(expression: string, from: string, to: string): string {
  return expression.replace(new RegExp(`^${from}(?=\\.|$)`), to);
}

function uniqueName(baseName: string, usedNames: Set<string>): string {
  const normalizedBase = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(baseName) ? baseName : 'value';
  let candidate = normalizedBase;
  let index = 2;

  while (usedNames.has(candidate)) {
    candidate = `${normalizedBase}${index}`;
    index += 1;
  }

  usedNames.add(candidate);
  return candidate;
}

function renderImportStatement(entry: ImportEntry): string {
  if (entry.importKind === 'default') {
    return `import ${entry.localName} from '${entry.importPath}';`;
  }

  if (entry.importKind === 'namespace') {
    return `import * as ${entry.localName} from '${entry.importPath}';`;
  }

  if (entry.localName !== entry.importSourceName) {
    return `import { ${entry.importSourceName} as ${entry.localName} } from '${entry.importPath}';`;
  }

  return `import { ${entry.localName} } from '${entry.importPath}';`;
}

function createImportRegistry(currentFile: string) {
  const usedNames = new Set<string>();
  const entries = new Map<string, ImportEntry>();

  function register(entry: Omit<ImportEntry, 'localName'> & { preferredLocalName: string }): string {
    const existing = entries.get(entry.key);
    if (existing) {
      return existing.localName;
    }

    const localName = uniqueName(entry.preferredLocalName, usedNames);
    entries.set(entry.key, {
      key: entry.key,
      importKind: entry.importKind,
      importPath: entry.importPath,
      importSourceName: entry.importSourceName,
      localName,
    });
    return localName;
  }

  return {
    addImportedSource(source: ImportedValueSource, preferredLocalName?: string): string {
      const importPath = toModuleImport(currentFile, source.sourceFile);
      const localName = register({
        key: `${importPath}|${source.importKind}|${source.importSourceName}|${source.importName}`,
        importKind: source.importKind,
        importPath,
        importSourceName: source.importSourceName,
        preferredLocalName: preferredLocalName ?? source.importName,
      });
      return rewriteRootIdentifier(source.accessExpression, source.importName, localName);
    },

    addDefaultFileImport(sourceFile: string, preferredLocalName: string): string {
      const importPath = toModuleImport(currentFile, sourceFile);
      return register({
        key: `${importPath}|default`,
        importKind: 'default',
        importPath,
        importSourceName: 'default',
        preferredLocalName,
      });
    },

    addNamedFileImport(sourceFile: string, importSourceName: string, preferredLocalName = importSourceName): string {
      const importPath = toModuleImport(currentFile, sourceFile);
      return register({
        key: `${importPath}|named|${importSourceName}`,
        importKind: 'named',
        importPath,
        importSourceName,
        preferredLocalName,
      });
    },

    render(): string {
      return [...entries.values()].map((entry) => renderImportStatement(entry)).join('\n');
    },
  };
}

function isGeneratedDto(definition: NormalizedDtoDefinition | undefined): definition is NormalizedGeneratedDtoDefinition {
  return Boolean(definition && definition.mode === 'generated');
}

function tableImportStatement(currentFile: string, resource: NormalizedResourceDefinition): string {
  return renderImportStatement({
    key: 'table',
    importKind: resource.source.tableImportKind,
    importPath: toModuleImport(
      currentFile,
      path.resolve(path.dirname(resource.source.sourceFile), resource.source.tableImportSourceFile),
    ),
    importSourceName: resource.source.tableImportSourceName,
    localName: resource.source.tableImportName,
  });
}

function dbTypeExpression(config: NormalizedApiKitConfig, resource: NormalizedResourceDefinition): string {
  if (config.dbSchemaSource) {
    return 'NodePgDatabase<typeof schema>';
  }

  return `NodePgDatabase<{ ${resource.source.tableQueryName}: typeof ${resource.source.tableAccessExpression} }>`;
}

function commonDbImportStatement(currentFile: string, outputPath: string, hasSchema: boolean): string {
  const importPath = toModuleImport(currentFile, path.join(outputPath, 'common', 'db.ts'));
  return hasSchema
    ? `import { DB_PROVIDER_TOKEN, schema } from '${importPath}';`
    : `import { DB_PROVIDER_TOKEN } from '${importPath}';`;
}

function validationImportStatement(currentFile: string, outputPath: string): string {
  return `import { validateResourceInput } from '${toModuleImport(currentFile, path.join(outputPath, 'common', 'validation.ts'))}';`;
}

function paginationImportStatement(currentFile: string, outputPath: string): string {
  return `import type { PaginatedResult } from '${toModuleImport(currentFile, path.join(outputPath, 'common', 'types.ts'))}';`;
}

function dtoTypeExpression(
  currentFile: string,
  dtoDir: string,
  registry: ReturnType<typeof createImportRegistry>,
  definition: NormalizedDtoDefinition,
): string {
  if (isGeneratedDto(definition)) {
    return registry.addNamedFileImport(path.join(dtoDir, definition.fileName), definition.className);
  }

  return registry.addImportedSource(definition.source);
}

function resourceIdParamsIdentity(resource: NormalizedResourceDefinition): {
  mode: 'generated';
  kind: 'params';
  className: string;
  fileName: string;
} {
  return {
    mode: 'generated',
    kind: 'params',
    className: `${pascalCase(resource.singularName)}IdParamsDto`,
    fileName: `${kebabCase(resource.singularName)}-id.params.dto.ts`,
  };
}

function usesGeneratedIdParams(resource: NormalizedResourceDefinition): boolean {
  const idType = resource.generatedDtos.idField?.tsType ?? 'string';
  if (idType === 'number' || idType === 'bigint') {
    return false;
  }

  return resource.functions.update.enabled
    || (resource.functions.findOne.enabled && isGeneratedDto(resource.functions.findOne.input))
    || (resource.functions.delete.enabled && isGeneratedDto(resource.functions.delete.input));
}

function buildGeneratedDtoContext(resource: NormalizedResourceDefinition): GeneratedDtoTemplateContext {
  return {
    ...(isGeneratedDto(resource.functions.find.input) ? { findInput: resource.functions.find.input } : {}),
    ...(isGeneratedDto(resource.functions.create.input) ? { createInput: resource.functions.create.input } : {}),
    ...(isGeneratedDto(resource.functions.update.input) ? { updateInput: resource.functions.update.input } : {}),
    ...(usesGeneratedIdParams(resource) ? { idParams: resourceIdParamsIdentity(resource) } : {}),
    ...(resource.functions.find.output && isGeneratedDto(resource.functions.find.output) ? { findOutput: resource.functions.find.output } : {}),
    ...(resource.functions.findOne.output && isGeneratedDto(resource.functions.findOne.output) ? { findOneOutput: resource.functions.findOne.output } : {}),
    ...(resource.functions.create.output && isGeneratedDto(resource.functions.create.output) ? { createOutput: resource.functions.create.output } : {}),
    ...(resource.functions.update.output && isGeneratedDto(resource.functions.update.output) ? { updateOutput: resource.functions.update.output } : {}),
  };
}

function dtoTargetPath(dtoDir: string, definition: { fileName: string } | undefined, enabled: boolean): string {
  return enabled && definition ? path.join(dtoDir, definition.fileName) : '';
}

function buildIndexExports(resource: NormalizedResourceDefinition, dto: GeneratedDtoTemplateContext): string[] {
  return [
    `export * from './${resource.fileNames.module.replace('.ts', '')}';`,
    `export * from './${resource.fileNames.controller.replace('.ts', '')}';`,
    `export * from './${resource.fileNames.service.replace('.ts', '')}';`,
    ...((resource.functions.find.enabled || resource.functions.findOne.enabled)
      ? [`export * from './${resource.fileNames.query.replace('.ts', '')}';`]
      : []),
    ...(dto.findInput && (resource.functions.find.enabled || resource.functions.findOne.enabled)
      ? [`export * from './dto/${dto.findInput.fileName.replace('.ts', '')}';`]
      : []),
    ...(dto.createInput && resource.functions.create.enabled
      ? [`export * from './dto/${dto.createInput.fileName.replace('.ts', '')}';`]
      : []),
    ...(dto.updateInput && resource.functions.update.enabled
      ? [`export * from './dto/${dto.updateInput.fileName.replace('.ts', '')}';`]
      : []),
    ...(dto.idParams
      ? [`export * from './dto/${dto.idParams.fileName.replace('.ts', '')}';`]
      : []),
    ...(dto.findOutput && resource.functions.find.enabled
      ? [`export * from './dto/${dto.findOutput.fileName.replace('.ts', '')}';`]
      : []),
    ...(dto.findOneOutput && resource.functions.findOne.enabled
      ? [`export * from './dto/${dto.findOneOutput.fileName.replace('.ts', '')}';`]
      : []),
    ...(dto.createOutput && resource.functions.create.enabled
      ? [`export * from './dto/${dto.createOutput.fileName.replace('.ts', '')}';`]
      : []),
    ...(dto.updateOutput && resource.functions.update.enabled
      ? [`export * from './dto/${dto.updateOutput.fileName.replace('.ts', '')}';`]
      : []),
  ];
}

function apiOperationDecorator(fn: NormalizedResourceFunctionDefinition, docsEnabled: boolean): string | null {
  if (!docsEnabled) {
    return null;
  }

  const parts = [`operationId: ${quote(fn.operationId)}`, `summary: ${quote(fn.summary)}`];
  if (fn.description) {
    parts.push(`description: ${quote(fn.description)}`);
  }

  return `@ApiOperation({ ${parts.join(', ')} })`;
}

function hookCallLines(hooks: Array<{ name: string; description?: string }>, spaces: number): string[] {
  return hooks.flatMap((hook) => {
    const lines: string[] = [];
    if (hook.description) {
      lines.push(`${' '.repeat(spaces)}// ${hook.description}`);
    }
    lines.push(`${' '.repeat(spaces)}await ${hook.name}(context);`);
    return lines;
  });
}

function buildFunctionHooks(
  config: NormalizedApiKitConfig,
  resource: NormalizedResourceDefinition,
  functionName: ResourceFunctionName,
  registry: ReturnType<typeof createImportRegistry>,
): {
  before: Array<{ name: string; description?: string }>;
  after: Array<{ name: string; description?: string }>;
} {
  const toHookCall = (hook: NormalizedHookDefinition) => ({
    name: registry.addDefaultFileImport(hook.sourceFile, hook.suggestedName),
    ...(hook.description ? { description: hook.description } : {}),
  });

  return {
    before: [
      ...(config.hooks?.before ?? []),
      ...(config.hooks?.functions[functionName].before ?? []),
      ...(resource.functions[functionName].hooks.before ?? []),
    ].map(toHookCall),
    after: [
      ...(resource.functions[functionName].hooks.after ?? []),
      ...(config.hooks?.functions[functionName].after ?? []),
      ...(config.hooks?.after ?? []),
    ].map(toHookCall),
  };
}

function buildControllerImportConfig(resource: NormalizedResourceDefinition): ControllerImportConfig {
  const commonImports = new Set(['Controller']);
  const idTsType = resource.generatedDtos.idField?.tsType ?? 'string';

  if (resource.functions.find.enabled) {
    commonImports.add('Get');
    commonImports.add('Query');
  }

  if (resource.functions.findOne.enabled) {
    commonImports.add('Get');
    commonImports.add('Param');
    commonImports.add('Query');
  }

  if (resource.functions.create.enabled) {
    commonImports.add('Post');
    commonImports.add('Body');
  }

  if (resource.functions.update.enabled) {
    commonImports.add('Patch');
    commonImports.add('Param');
    commonImports.add('Body');
  }

  if (resource.functions.delete.enabled) {
    commonImports.add('Delete');
    commonImports.add('HttpCode');
    commonImports.add('Param');
  }

  const hasGuards = resource.guards.length > 0 || functionNames.some((functionName) => resource.functions[functionName].guards.length > 0);
  if (hasGuards) {
    commonImports.add('UseGuards');
  }

  if (idTsType === 'number') {
    commonImports.add('ParseIntPipe');
  }

  if (idTsType === 'bigint') {
    commonImports.add('BadRequestException');
  }

  return {
    commonImports: [...commonImports],
    usesBigIntIdParser: idTsType === 'bigint',
    usesNumberIdPipe: idTsType === 'number',
  };
}

function renderControllerMethods(
  resource: NormalizedResourceDefinition,
  controllerPath: string,
  dtoDir: string,
  registry: ReturnType<typeof createImportRegistry>,
  controllerImports: ControllerImportConfig,
  generatedIdParams: GeneratedDtoTemplateContext['idParams'],
): { methods: string; rootGuardDecorator: string | null } {
  const methods: string[] = [];
  const docsEnabled = resource.docs.enabled;
  const idFieldName = resource.generatedDtos.idField?.name ?? 'id';

  const queryType = resource.functions.find.enabled || resource.functions.findOne.enabled
    ? dtoTypeExpression(controllerPath, dtoDir, registry, resource.functions.find.input)
    : null;
  const createInputType = resource.functions.create.enabled
    ? dtoTypeExpression(controllerPath, dtoDir, registry, resource.functions.create.input)
    : null;
  const updateInputType = resource.functions.update.enabled
    ? dtoTypeExpression(controllerPath, dtoDir, registry, resource.functions.update.input)
    : null;
  const findOneParamsType = resource.functions.findOne.enabled && !controllerImports.usesNumberIdPipe && !controllerImports.usesBigIntIdParser
    ? isGeneratedDto(resource.functions.findOne.input)
      ? registry.addNamedFileImport(
          path.join(dtoDir, generatedIdParams?.fileName ?? resource.functions.findOne.input.fileName),
          generatedIdParams?.className ?? resource.functions.findOne.input.className,
        )
      : registry.addImportedSource(resource.functions.findOne.input.source)
    : null;
  const updateParamsType = resource.functions.update.enabled && !controllerImports.usesNumberIdPipe && !controllerImports.usesBigIntIdParser && generatedIdParams
    ? registry.addNamedFileImport(path.join(dtoDir, generatedIdParams.fileName), generatedIdParams.className)
    : null;
  const deleteParamsType = resource.functions.delete.enabled && !controllerImports.usesNumberIdPipe && !controllerImports.usesBigIntIdParser
    ? isGeneratedDto(resource.functions.delete.input)
      ? registry.addNamedFileImport(
          path.join(dtoDir, generatedIdParams?.fileName ?? resource.functions.delete.input.fileName),
          generatedIdParams?.className ?? resource.functions.delete.input.className,
        )
      : registry.addImportedSource(resource.functions.delete.input.source)
    : null;

  const rootGuardDecorator = resource.guards.length > 0
    ? `@UseGuards(${resource.guards.map((guard) => registry.addImportedSource(guard)).join(', ')})`
    : null;

  const functionGuardDecorator = (functionName: ResourceFunctionName): string | null => {
    const guards = resource.functions[functionName].guards;
    return guards.length > 0
      ? `@UseGuards(${guards.map((guard) => registry.addImportedSource(guard)).join(', ')})`
      : null;
  };

  if (resource.functions.find.enabled && queryType) {
    methods.push(
      renderPartialTemplate('controller/find-method.ejs', {
        docsDecorator: apiOperationDecorator(resource.functions.find, docsEnabled),
        guardsDecorator: functionGuardDecorator('find'),
        queryType,
      }).trim(),
    );
  }

  if (resource.functions.findOne.enabled && queryType) {
    const signature = controllerImports.usesNumberIdPipe
      ? `async findOne(@Param('id', ParseIntPipe) id: number, @Query() query: ${queryType}) {`
      : controllerImports.usesBigIntIdParser
        ? `async findOne(@Param('id') id: string, @Query() query: ${queryType}) {`
        : `async findOne(@Param() params: ${findOneParamsType}, @Query() query: ${queryType}) {`;
    const call = controllerImports.usesNumberIdPipe
      ? '  return this.service.findOne(id, query);'
      : controllerImports.usesBigIntIdParser
        ? '  return this.service.findOne(this.parseBigIntId(id), query);'
        : `  return this.service.findOne(params.${idFieldName}, query);`;

    methods.push(
      renderPartialTemplate('controller/find-one-method.ejs', {
        docsDecorator: apiOperationDecorator(resource.functions.findOne, docsEnabled),
        guardsDecorator: functionGuardDecorator('findOne'),
        signature,
        call,
      }).trim(),
    );
  }

  if (resource.functions.create.enabled && createInputType) {
    methods.push(
      renderPartialTemplate('controller/create-method.ejs', {
        docsDecorator: apiOperationDecorator(resource.functions.create, docsEnabled),
        guardsDecorator: functionGuardDecorator('create'),
        inputType: createInputType,
      }).trim(),
    );
  }

  if (resource.functions.update.enabled && updateInputType) {
    const signature = controllerImports.usesNumberIdPipe
      ? `async update(@Param('id', ParseIntPipe) id: number, @Body() body: ${updateInputType}) {`
      : controllerImports.usesBigIntIdParser
        ? `async update(@Param('id') id: string, @Body() body: ${updateInputType}) {`
        : `async update(@Param() params: ${updateParamsType}, @Body() body: ${updateInputType}) {`;
    const call = controllerImports.usesNumberIdPipe
      ? '  return this.service.update(id, body);'
      : controllerImports.usesBigIntIdParser
        ? '  return this.service.update(this.parseBigIntId(id), body);'
        : `  return this.service.update(params.${idFieldName}, body);`;

    methods.push(
      renderPartialTemplate('controller/update-method.ejs', {
        docsDecorator: apiOperationDecorator(resource.functions.update, docsEnabled),
        guardsDecorator: functionGuardDecorator('update'),
        signature,
        call,
      }).trim(),
    );
  }

  if (resource.functions.delete.enabled) {
    const signature = controllerImports.usesNumberIdPipe
      ? 'async delete(@Param(\'id\', ParseIntPipe) id: number) {'
      : controllerImports.usesBigIntIdParser
        ? 'async delete(@Param(\'id\') id: string) {'
        : `async delete(@Param() params: ${deleteParamsType}) {`;
    const call = controllerImports.usesNumberIdPipe
      ? '  await this.service.delete(id);'
      : controllerImports.usesBigIntIdParser
        ? '  await this.service.delete(this.parseBigIntId(id));'
        : `  await this.service.delete(params.${idFieldName});`;

    methods.push(
      renderPartialTemplate('controller/delete-method.ejs', {
        docsDecorator: apiOperationDecorator(resource.functions.delete, docsEnabled),
        guardsDecorator: functionGuardDecorator('delete'),
        signature,
        call,
      }).trim(),
    );
  }

  return {
    methods: methods.join('\n\n\n'),
    rootGuardDecorator,
  };
}

function buildControllerContext(
  resource: NormalizedResourceDefinition,
  resourceDir: string,
  dtoDir: string,
  dto: GeneratedDtoTemplateContext,
): ResourceTemplateContext['controller'] {
  const controllerPath = path.join(resourceDir, resource.fileNames.controller);
  const registry = createImportRegistry(controllerPath);
  const controllerImports = buildControllerImportConfig(resource);
  registry.addNamedFileImport(path.join(resourceDir, resource.fileNames.service), resource.classNames.service);

  const { methods, rootGuardDecorator } = renderControllerMethods(
    resource,
    controllerPath,
    dtoDir,
    registry,
    controllerImports,
    dto.idParams,
  );

  const importsBlock = joinBlocks([
    `import { ${controllerImports.commonImports.join(', ')} } from '@nestjs/common';`,
    resource.docs.enabled ? "import { ApiOperation, ApiTags } from '@nestjs/swagger';" : null,
    registry.render(),
  ]);

  const apiTagsDecorator = resource.docs.enabled
    ? `@ApiTags(${(resource.docs.tags ?? []).map((tag) => quote(tag)).join(', ')})`
    : null;

  return {
    importsBlock,
    apiTagsDecorator,
    guardDecorator: rootGuardDecorator,
    bigIntParserMethod: controllerImports.usesBigIntIdParser
      ? renderPartialTemplate('controller/big-int-parser-method.ejs', {}).trim()
      : null,
    methods,
  };
}

function buildValidationExpressions(
  resource: NormalizedResourceDefinition,
  registry: ReturnType<typeof createImportRegistry>,
): Record<ResourceFunctionName, string | null> {
  return Object.fromEntries(
    functionNames.map((functionName) => [
      functionName,
      resource.functions[functionName].validation
        ? registry.addImportedSource(resource.functions[functionName].validation!, `${functionName}ValidationSchema`)
        : null,
    ]),
  ) as Record<ResourceFunctionName, string | null>;
}

function buildServiceContext(
  config: NormalizedApiKitConfig,
  resource: NormalizedResourceDefinition,
  resourceDir: string,
  dtoDir: string,
): ResourceTemplateContext['service'] {
  const servicePath = path.join(resourceDir, resource.fileNames.service);
  const registry = createImportRegistry(servicePath);
  const queryEnabled = resource.functions.find.enabled || resource.functions.findOne.enabled;
  const findInputType = queryEnabled ? dtoTypeExpression(servicePath, dtoDir, registry, resource.functions.find.input) : null;
  const createInputType = resource.functions.create.enabled ? dtoTypeExpression(servicePath, dtoDir, registry, resource.functions.create.input) : null;
  const updateInputType = resource.functions.update.enabled ? dtoTypeExpression(servicePath, dtoDir, registry, resource.functions.update.input) : null;
  const findOutputType = resource.functions.find.output ? dtoTypeExpression(servicePath, dtoDir, registry, resource.functions.find.output) : null;
  const findOneOutputType = resource.functions.findOne.output ? dtoTypeExpression(servicePath, dtoDir, registry, resource.functions.findOne.output) : null;
  const createOutputType = resource.functions.create.output ? dtoTypeExpression(servicePath, dtoDir, registry, resource.functions.create.output) : null;
  const updateOutputType = resource.functions.update.output ? dtoTypeExpression(servicePath, dtoDir, registry, resource.functions.update.output) : null;
  const queryClass = queryEnabled ? registry.addNamedFileImport(path.join(resourceDir, resource.fileNames.query), resource.classNames.query) : null;
  const validationExpressions = buildValidationExpressions(resource, registry);
  const idType = resource.generatedDtos.idField?.tsType ?? 'string';
  const idFieldName = resource.generatedDtos.idField?.name ?? 'id';
  const dbType = dbTypeExpression(config, resource);

  const renderMethod = (
    templatePath: string,
    functionName: ResourceFunctionName,
    locals: Record<string, unknown>,
  ): string => {
    const hooks = buildFunctionHooks(config, resource, functionName, registry);
    return renderPartialTemplate(templatePath, {
      resourceName: resource.name,
      queryClass,
      validationExpression: validationExpressions[functionName],
      hasHooks: hooks.before.length > 0 || hooks.after.length > 0,
      beforeHookLines: hookCallLines(hooks.before, 4),
      afterHookLines: hookCallLines(hooks.after, 4),
      beforeHookLinesTransactional: hookCallLines(hooks.before, 6),
      afterHookLinesTransactional: hookCallLines(hooks.after, 6),
      ...locals,
    }).trimEnd();
  };

  const paginationEnabled = resource.query.pagination.enabled !== false;
  const findMethod = resource.functions.find.enabled && findInputType && findOutputType && queryClass
    ? renderMethod('service/find-method.ejs', 'find', {
        queryType: findInputType,
        returnType: paginationEnabled ? `PaginatedResult<${findOutputType}>` : `${findOutputType}[]`,
        outputType: findOutputType,
      })
    : '';
  const findOneMethod = resource.functions.findOne.enabled && findInputType && findOneOutputType && queryClass
    ? renderMethod('service/find-one-method.ejs', 'findOne', {
        queryType: findInputType,
        outputType: findOneOutputType,
        idType,
      })
    : '';
  const createMethod = resource.functions.create.enabled && createInputType && createOutputType
    ? renderMethod('service/create-method.ejs', 'create', {
        inputType: createInputType,
        outputType: createOutputType,
        transactional: resource.functions.create.transactional,
        table: resource.source.tableAccessExpression,
      })
    : '';
  const updateMethod = resource.functions.update.enabled && updateInputType && updateOutputType
    ? renderMethod('service/update-method.ejs', 'update', {
        inputType: updateInputType,
        outputType: updateOutputType,
        transactional: resource.functions.update.transactional,
        table: resource.source.tableAccessExpression,
        idType,
        idFieldName,
      })
    : '';
  const deleteMethod = resource.functions.delete.enabled
    ? renderMethod('service/delete-method.ejs', 'delete', {
        transactional: resource.functions.delete.transactional,
        table: resource.source.tableAccessExpression,
        idType,
        idFieldName,
      })
    : '';

  const importsBlock = joinBlocks([
    tableImportStatement(servicePath, resource),
    commonDbImportStatement(servicePath, config.outputPath, Boolean(config.dbSchemaSource)),
    resource.functions.find.enabled && paginationEnabled ? paginationImportStatement(servicePath, config.outputPath) : null,
    functionNames.some((functionName) => Boolean(validationExpressions[functionName]))
      ? validationImportStatement(servicePath, config.outputPath)
      : null,
    registry.render(),
  ]);

  return {
    importsBlock,
    dbType,
    findMethod,
    findOneMethod,
    createMethod,
    updateMethod,
    deleteMethod,
  };
}

function buildQueryContext(
  config: NormalizedApiKitConfig,
  resource: NormalizedResourceDefinition,
  resourceDir: string,
  dtoDir: string,
): ResourceTemplateContext['query'] {
  const queryEnabled = resource.functions.find.enabled || resource.functions.findOne.enabled;
  if (!queryEnabled) {
    return {
      enabled: false,
      importsBlock: '',
      drizzleImports: '',
      dbType: '',
      findManyMethod: '',
      findOneMethod: '',
      resolveConditionMethod: '',
      resolveOrderByMethod: null,
    };
  }

  const queryPath = path.join(resourceDir, resource.fileNames.query);
  const registry = createImportRegistry(queryPath);
  const queryType = dtoTypeExpression(queryPath, dtoDir, registry, resource.functions.find.input);
  const findOutputType = resource.functions.find.output ? dtoTypeExpression(queryPath, dtoDir, registry, resource.functions.find.output) : null;
  const findOneOutputType = resource.functions.findOne.output ? dtoTypeExpression(queryPath, dtoDir, registry, resource.functions.findOne.output) : null;
  const paginationEnabled = resource.query.pagination.enabled !== false;
  const drizzleImports = [
    ...(paginationEnabled && resource.functions.find.enabled ? ['count'] : []),
    ...(resource.functions.findOne.enabled ? ['eq'] : []),
    ...((resource.query.sorts ?? []).length > 0 && resource.functions.find.enabled ? ['asc', 'desc'] : []),
  ];
  const commonQueryImports = [
    ...((resource.query.filters ?? []).length > 0 ? ['buildAllowedColumnCondition'] : []),
    ...((resource.query.relations ?? []).length > 0 ? ['buildRequestedRelations'] : []),
    'GeneratedResourceQueryBase',
    ...(paginationEnabled && resource.functions.find.enabled ? ['toPositiveNumber'] : []),
    'type ParsedFilter',
  ];

  const importsBlock = joinBlocks([
    tableImportStatement(queryPath, resource),
    config.dbSchemaSource ? `import { schema } from '${toModuleImport(queryPath, path.join(config.outputPath, 'common', 'db.ts'))}';` : null,
    paginationEnabled && resource.functions.find.enabled ? paginationImportStatement(queryPath, config.outputPath) : null,
    `import { ${commonQueryImports.join(', ')} } from '${toModuleImport(queryPath, path.join(config.outputPath, 'common', 'query.ts'))}';`,
    registry.render(),
  ]);

  return {
    enabled: true,
    importsBlock,
    drizzleImports: drizzleImports.join(', '),
    dbType: dbTypeExpression(config, resource),
    findManyMethod: resource.functions.find.enabled && findOutputType
      ? renderPartialTemplate('query/find-many-method.ejs', {
          queryType,
          outputType: findOutputType,
          tableAccessExpression: resource.source.tableAccessExpression,
          tableQueryName: resource.source.tableQueryName,
          pagination: resource.query.pagination,
          paginationEnabled,
          relations: resource.query.relations ?? [],
          relationNamesLiteral: (resource.query.relations ?? []).map((relation) => quote(relation.name)).join(', '),
          sorts: resource.query.sorts ?? [],
          defaultSortsLiteral: (resource.query.sorts ?? [])
            .filter((sort) => sort.defaultOrder)
            .map((sort) => `${sort.defaultOrder === 'desc' ? 'desc' : 'asc'}(${resource.source.tableAccessExpression}.${sort.field})`)
            .join(', '),
          returnType: paginationEnabled ? `PaginatedResult<${findOutputType}>` : `${findOutputType}[]`,
        }).trimEnd()
      : '',
    findOneMethod: resource.functions.findOne.enabled && findOneOutputType
      ? renderPartialTemplate('query/find-one-method.ejs', {
          queryType,
          outputType: findOneOutputType,
          idType: resource.generatedDtos.idField?.tsType ?? 'string',
          idFieldName: resource.generatedDtos.idField?.name ?? 'id',
          tableAccessExpression: resource.source.tableAccessExpression,
          tableQueryName: resource.source.tableQueryName,
          relations: resource.query.relations ?? [],
          relationNamesLiteral: (resource.query.relations ?? []).map((relation) => quote(relation.name)).join(', '),
        }).trimEnd()
      : '',
    resolveConditionMethod: renderPartialTemplate('query/resolve-condition-method.ejs', {
      filters: resource.query.filters ?? [],
      tableAccessExpression: resource.source.tableAccessExpression,
    }).trimEnd(),
    resolveOrderByMethod: (resource.query.sorts ?? []).length > 0
      ? renderPartialTemplate('query/resolve-order-by-method.ejs', {
          sorts: resource.query.sorts ?? [],
          tableAccessExpression: resource.source.tableAccessExpression,
        }).trimEnd()
      : null,
  };
}

export function buildResourceTemplateContext(
  config: NormalizedApiKitConfig,
  resource: NormalizedResourceDefinition,
): ResourceTemplateContext {
  const resourceDir = path.join(config.outputPath, resource.pluralName);
  const dtoDir = path.join(resourceDir, 'dto');
  const dto = buildGeneratedDtoContext(resource);
  const queryEnabled = resource.functions.find.enabled || resource.functions.findOne.enabled;
  const controller = buildControllerContext(resource, resourceDir, dtoDir, dto);
  const service = buildServiceContext(config, resource, resourceDir, dtoDir);
  const query = buildQueryContext(config, resource, resourceDir, dtoDir);
  const { original: _original, ...serializableResource } = resource;

  return {
    generatedHeader: GENERATED_HEADER,
    resourceDir,
    dtoDir,
    targets: {
      findInputDto: dtoTargetPath(dtoDir, dto.findInput, Boolean(dto.findInput && (resource.functions.find.enabled || resource.functions.findOne.enabled))),
      createInputDto: dtoTargetPath(dtoDir, dto.createInput, Boolean(dto.createInput && resource.functions.create.enabled)),
      updateInputDto: dtoTargetPath(dtoDir, dto.updateInput, Boolean(dto.updateInput && resource.functions.update.enabled)),
      idParamsDto: dtoTargetPath(dtoDir, dto.idParams, Boolean(dto.idParams)),
      findOutputDto: dtoTargetPath(dtoDir, dto.findOutput, Boolean(dto.findOutput && resource.functions.find.enabled)),
      findOneOutputDto: dtoTargetPath(dtoDir, dto.findOneOutput, Boolean(dto.findOneOutput && resource.functions.findOne.enabled)),
      createOutputDto: dtoTargetPath(dtoDir, dto.createOutput, Boolean(dto.createOutput && resource.functions.create.enabled)),
      updateOutputDto: dtoTargetPath(dtoDir, dto.updateOutput, Boolean(dto.updateOutput && resource.functions.update.enabled)),
      metadata: path.join(resourceDir, resource.fileNames.metadata),
      service: path.join(resourceDir, resource.fileNames.service),
      query: queryEnabled ? path.join(resourceDir, resource.fileNames.query) : '',
      controller: path.join(resourceDir, resource.fileNames.controller),
      module: path.join(resourceDir, resource.fileNames.module),
      index: path.join(resourceDir, 'index.ts'),
    },
    resource: serializableResource,
    dto,
    controller,
    service,
    query,
    indexExports: buildIndexExports(resource, dto),
  };
}

export function buildRootTemplateContext(config: NormalizedApiKitConfig): RootTemplateContext {
  const commonDbPath = path.join(config.outputPath, 'common', 'db.ts');
  const schemaImportAlias = '__apiKitSchemaSource';

  return {
    generatedHeader: GENERATED_HEADER,
    outputPath: config.outputPath,
    rootModuleClassName: config.rootModuleClassName,
    rootModuleFileName: config.rootModuleFileName,
    dbProviderToken: resolveDbProviderToken(config),
    ...(config.dbSchemaSource
      ? {
          dbSchemaImportPath: toModuleImport(commonDbPath, config.dbSchemaSource.sourceFile),
          dbSchemaImportKind: config.dbSchemaSource.importKind,
          dbSchemaImportName: schemaImportAlias,
          dbSchemaImportSourceName: config.dbSchemaSource.importSourceName,
          dbSchemaAccessExpression: rewriteRootIdentifier(
            config.dbSchemaSource.accessExpression,
            config.dbSchemaSource.importName,
            schemaImportAlias,
          ),
        }
      : {}),
    ...(config.validation
      ? {
          validation: config.validation.engineSource
            ? {
                engineImportPath: toModuleImport(commonDbPath, config.validation.engineSource.sourceFile),
                engineImportKind: config.validation.engineSource.importKind,
                engineImportName: config.validation.engineSource.importName,
                engineImportSourceName: config.validation.engineSource.importSourceName,
                engineAccessExpression: config.validation.engineSource.accessExpression,
              }
            : {},
        }
      : {}),
    targets: {
      rootModule: path.join(config.outputPath, config.rootModuleFileName),
      index: path.join(config.outputPath, 'index.ts'),
      commonDb: commonDbPath,
      commonTypes: path.join(config.outputPath, 'common', 'types.ts'),
      commonQuery: path.join(config.outputPath, 'common', 'query.ts'),
      commonValidation: path.join(config.outputPath, 'common', 'validation.ts'),
      commonIndex: path.join(config.outputPath, 'common', 'index.ts'),
    },
    resources: config.resources.map((resource) => ({
      pluralName: resource.pluralName,
      moduleClassName: resource.classNames.module,
    })),
  };
}
